### ISSUE TITLE
ReferenceError: m is not defined

### ISSUE THREAD

**Issue by hbfs** [farzher/mithril-livescript-todomvc#2]
```
$ node app.js

~/Downloads/mithril-livescript-todomvc/app.js:137
m.route(document.getElementById('todoapp'), '/', {
^

ReferenceError: m is not defined
    at Object.<anonymous> (~/Downloads/mithril-livescript-todomvc/app.js:137:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

What am I missing here?

**Comment by farzher** [comment]
This isn't a node application. It's just a static webpage (app.js runs in your browser)
Just point your browser to the index.html file

**Comment by hbfs** [comment]
Derp. Thanks, eventually figured that out. The goal was to benchmark it as if running on a server (network + paint + ... = total timing) with a specific set of actions. Gave up with node and just did a bash script + python
